This notebook is used for testing. It checks if all the evaluaion data is complete

In [53]:
import pandas as pd

In [54]:
evaluation_path = '../evaluation/'
evaluation_summary_path = f'{evaluation_path}evaluation_summary.csv'

evaluation_summary = pd.read_csv(evaluation_summary_path)

In [55]:
evaluation_summary.head()

,Model,Dataset,Skeleton Encoder Layers,Loss Version,Minimum Support,Maximum Support,Total Entries,Match Sum,Match Percentage,Number of Samples
0,mmsr_se1_oldloss,train_nc,1.0,old,-40.0,-30.0,214,1,0.467290,500.0
1,mmsr_se1_oldloss,train_nc,1.0,old,-40.0,-30.0,212,1,0.471698,500.0
2,mmsr_se1_oldloss,train_nc,1.0,old,-40.0,-30.0,212,1,0.471698,500.0
3,mmsr_se1_oldloss,train_nc,1.0,old,-40.0,-30.0,213,1,0.469484,500.0
4,mmsr_se1_oldloss,train_nc,1.0,old,-40.0,-30.0,213,1,0.469484,500.0

In [56]:
minimum_supports = range(-30, 11, 1)
support_range = 20
models = ['mmsr_se1_oldloss', 'mmsr_se5_oldloss', 'mmsr_se5_newloss', 'nsr']
number_of_samples = 500

for model in models:
    for minimum_support in minimum_supports:
        assert 10 == len(evaluation_summary[(evaluation_summary['Model'] == model) & 
                           (evaluation_summary['Minimum Support'] == minimum_support) & 
                           (evaluation_summary['Number of Samples'] == number_of_samples) &
                           (evaluation_summary['Maximum Support'] == minimum_support + support_range)]), f"Assertion failed for model {model} and minimum support {minimum_support}"

In [57]:
evaluation_summary[(evaluation_summary['Model'] == 'mmsr_se5_oldloss') & 
                           (evaluation_summary['Minimum Support'] == 8) & 
                           (evaluation_summary['Number of Samples'] == 500) &
                           (evaluation_summary['Maximum Support'] == 28)]

,Model,Dataset,Skeleton Encoder Layers,Loss Version,Minimum Support,Maximum Support,Total Entries,Match Sum,Match Percentage,Number of Samples
1978,mmsr_se5_oldloss,train_nc,5.0,old,8.0,28.0,228,17,7.456140,500.0
1979,mmsr_se5_oldloss,train_nc,5.0,old,8.0,28.0,229,18,7.860262,500.0
1980,mmsr_se5_oldloss,train_nc,5.0,old,8.0,28.0,230,22,9.565217,500.0
1981,mmsr_se5_oldloss,train_nc,5.0,old,8.0,28.0,230,18,7.826087,500.0
1982,mmsr_se5_oldloss,train_nc,5.0,old,8.0,28.0,229,16,6.986900,500.0
1983,mmsr_se5_oldloss,train_nc,5.0,old,8.0,28.0,228,15,6.578947,500.0
1984,mmsr_se5_oldloss,train_nc,5.0,old,8.0,28.0,229,16,6.986900,500.0
1985,mmsr_se5_oldloss,train_nc,5.0,old,8.0,28.0,230,20,8.695652,500.0
1986,mmsr_se5_oldloss,train_nc,5.0,old,8.0,28.0,230,19,8.260870,500.0
1987,mmsr_se5_oldloss,train_nc,5.0,old,8.0,28.0,229,17,7.423581,500.0

In [58]:
minimum_support = -10
support_range = 20
models = ['mmsr_se1_oldloss', 'mmsr_se5_oldloss', 'mmsr_se5_newloss', 'nsr']
numbers_of_samples = [100, 250, 500, 1000, 2000]

for model in models:
    for number_of_samples in numbers_of_samples:
        assert 10 == len(evaluation_summary[(evaluation_summary['Model'] == model) & 
                            (evaluation_summary['Minimum Support'] == minimum_support) & 
                            (evaluation_summary['Number of Samples'] == number_of_samples) &
                            (evaluation_summary['Maximum Support'] == minimum_support + support_range)]), f"Assertion failed for model {model} and number of samples {number_of_samples}"

In [59]:
evaluation_summary[(evaluation_summary['Model'] == 'mmsr_se1_oldloss') & 
                        (evaluation_summary['Minimum Support'] == -10) & 
                        (evaluation_summary['Number of Samples'] == 100) &
                        (evaluation_summary['Maximum Support'] == 10)]

,Model,Dataset,Skeleton Encoder Layers,Loss Version,Minimum Support,Maximum Support,Total Entries,Match Sum,Match Percentage,Number of Samples
400,mmsr_se1_oldloss,train_nc,1.0,old,-10.0,10.0,281,174,61.921708,100.0
407,mmsr_se1_oldloss,train_nc,1.0,old,-10.0,10.0,280,172,61.428571,100.0
415,mmsr_se1_oldloss,train_nc,1.0,old,-10.0,10.0,280,169,60.357143,100.0
416,mmsr_se1_oldloss,train_nc,1.0,old,-10.0,10.0,281,180,64.056940,100.0
430,mmsr_se1_oldloss,train_nc,1.0,old,-10.0,10.0,281,172,61.209964,100.0
433,mmsr_se1_oldloss,train_nc,1.0,old,-10.0,10.0,281,175,62.277580,100.0
435,mmsr_se1_oldloss,train_nc,1.0,old,-10.0,10.0,280,175,62.500000,100.0
436,mmsr_se1_oldloss,train_nc,1.0,old,-10.0,10.0,280,177,63.214286,100.0
439,mmsr_se1_oldloss,train_nc,1.0,old,-10.0,10.0,281,179,63.701068,100.0
442,mmsr_se1_oldloss,train_nc,1.0,old,-10.0,10.0,280,179,63.928571,100.0

In [60]:
minimum_supports = range(-40, 30, 10)
support_range = 10
models = ['mmsr_se1_oldloss', 'mmsr_se5_oldloss', 'mmsr_se5_newloss', 'nsr']
number_of_samples = 500

for model in models:
    for minimum_support in minimum_supports:
        assert 10 == len(evaluation_summary[(evaluation_summary['Model'] == model) & 
                            (evaluation_summary['Minimum Support'] == minimum_support) & 
                            (evaluation_summary['Number of Samples'] == number_of_samples) &
                            (evaluation_summary['Maximum Support'] == minimum_support + support_range)]), f"Assertion failed for model {model} and minimum support {minimum_support}"

In [61]:
evaluation_summary[(evaluation_summary['Model'] == 'nsr') & 
                            (evaluation_summary['Minimum Support'] == 30) & 
                            (evaluation_summary['Number of Samples'] == 500) &
                            (evaluation_summary['Maximum Support'] == 40)]

,Model,Dataset,Skeleton Encoder Layers,Loss Version,Minimum Support,Maximum Support,Total Entries,Match Sum,Match Percentage,Number of Samples
2588,nsr,train_nc,NaN,NaN,30.0,40.0,211,1,0.473934,500.0
2589,nsr,train_nc,NaN,NaN,30.0,40.0,211,0,0.000000,500.0
2590,nsr,train_nc,NaN,NaN,30.0,40.0,211,0,0.000000,500.0
2591,nsr,train_nc,NaN,NaN,30.0,40.0,212,0,0.000000,500.0
2592,nsr,train_nc,NaN,NaN,30.0,40.0,210,0,0.000000,500.0
2593,nsr,train_nc,NaN,NaN,30.0,40.0,211,0,0.000000,500.0
2594,nsr,train_nc,NaN,NaN,30.0,40.0,210,0,0.000000,500.0
2595,nsr,train_nc,NaN,NaN,30.0,40.0,210,0,0.000000,500.0
2596,nsr,train_nc,NaN,NaN,30.0,40.0,211,0,0.000000,500.0
2597,nsr,train_nc,NaN,NaN,30.0,40.0,212,0,0.000000,500.0

In [62]:
evaluation_summary['Model'].unique()

array(['mmsr_se1_oldloss', 'mmsr_se5_newloss', 'mmsr_se5_oldloss', 'nsr'],
      dtype=object)

In [63]:
minimum_supports = [-10, -5, -2.5, -1]
models = ['mmsr_se1_oldloss', 'mmsr_se5_oldloss', 'mmsr_se5_newloss', 'nsr']
number_of_samples = 500

for model in models:
    for minimum_support in minimum_supports:
        assert 10 == len(evaluation_summary[(evaluation_summary['Model'] == model) & 
                            (evaluation_summary['Minimum Support'] == minimum_support) & 
                            (evaluation_summary['Number of Samples'] == number_of_samples) &
                            (evaluation_summary['Maximum Support'] == -minimum_support)]), f"Assertion failed for model {model} and number of samples {minimum_support}"

In [64]:
evaluation_summary[(evaluation_summary['Model'] == 'mmsr_se5_newloss') & 
                            (evaluation_summary['Minimum Support'] == -10) & 
                            (evaluation_summary['Number of Samples'] == 500) &
                            (evaluation_summary['Maximum Support'] == 10)]

,Model,Dataset,Skeleton Encoder Layers,Loss Version,Minimum Support,Maximum Support,Total Entries,Match Sum,Match Percentage,Number of Samples
1143,mmsr_se5_newloss,train_nc,5.0,new,-10.0,10.0,280,197,70.357143,500.0
1149,mmsr_se5_newloss,train_nc,5.0,new,-10.0,10.0,281,193,68.683274,500.0
1157,mmsr_se5_newloss,train_nc,5.0,new,-10.0,10.0,281,200,71.174377,500.0
1167,mmsr_se5_newloss,train_nc,5.0,new,-10.0,10.0,279,197,70.609319,500.0
1172,mmsr_se5_newloss,train_nc,5.0,new,-10.0,10.0,280,202,72.142857,500.0
1174,mmsr_se5_newloss,train_nc,5.0,new,-10.0,10.0,281,194,69.039146,500.0
1177,mmsr_se5_newloss,train_nc,5.0,new,-10.0,10.0,280,197,70.357143,500.0
1181,mmsr_se5_newloss,train_nc,5.0,new,-10.0,10.0,281,200,71.174377,500.0
1183,mmsr_se5_newloss,train_nc,5.0,new,-10.0,10.0,280,196,70.000000,500.0
1191,mmsr_se5_newloss,train_nc,5.0,new,-10.0,10.0,280,196,70.000000,500.0